version: 0.2

phases:
  install:
    commands:
      - echo "Install step"
      - yum install -y awscli
  pre_build:
    commands:
      - echo "Pre-build checks"
      - test -f app/index.html
  build:
    commands:
      - echo "Build step"
      - mkdir -p dist
      - cp app/index.html dist/
  post_build:
    commands:
      - echo "Uploading artefact to S3"
      - aws s3 cp dist/index.html s3://<your-artifact-bucket>/index.html
      - echo "Deploying via SSM"
      - aws ssm send-command \
        --targets "Key=instanceIds,Values=i-030dfd73910eec9a9" \
        --document-name "AWS-RunShellScript" \
        --comment "Deploy web app" \
        --parameters 'commands=["aws s3 cp s3://<your-artifact-bucket>/index.html /var/www/html/index.html","sudo systemctl restart httpd"]'
artifacts:
  files:
    - dist/**/*