AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal infra for EC2 web app via CodeDeploy

Parameters:
  ProjectName:
    Type: String
    Default: devops-demo
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 key pair name
  InstanceType:
    Type: String
    Default: t3.micro

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags: [{ Key: Name, Value: !Sub '${ProjectName}-vpc' }]

  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachIgw:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags: [{ Key: Name, Value: !Sub '${ProjectName}-public' }]

  Rt:
    Type: AWS::EC2::RouteTable
    Properties: { VpcId: !Ref Vpc }
  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref Rt
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  RtAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref Rt

  Sg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/SSH
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 80, ToPort: 80, CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: 0.0.0.0/0 }
      Tags: [{ Key: Name, Value: !Sub '${ProjectName}-sg' }]

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Tags: [{ Key: Project, Value: !Ref ProjectName }]

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref InstanceRole ]

  Ec2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref KeyPairName
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: [ !Ref Sg ]
      Tags:
        - { Key: Name, Value: !Sub '${ProjectName}-web-ec2' }
        - { Key: Project, Value: !Ref ProjectName }
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail
          dnf update -y
          dnf install -y httpd ruby wget
          systemctl enable --now httpd
          echo "OK" > /var/www/html/health
          cd /tmp
          wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
          chmod +x install
          ./install auto
          systemctl enable --now codedeploy-agent

Outputs:
  PublicIp:
    Description: Public IP of the web server
    Value: !GetAtt Ec2.PublicIp
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref Ec2
  SgId:
    Description: Security Group ID
    Value: !Ref Sg